Controllers/HomeController.cs
using Eventix.Data;
using Eventix.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;

namespace Eventix.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly EventixContext _context;

        public HomeController(ILogger<HomeController> logger, EventixContext context)
        {
            _logger = logger;
            _context = context;
        }

        // GET: Performances
        public async Task<IActionResult> Index()
        {
            var performances = await _context.Performance
                .OrderByDescending(m => m.PerformanceDate)
                .Include(p => p.Category)
                .Include(p => p.Purchases)
                .ToListAsync();

            return View(performances);
        }

        // GET: Performances/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var photo = await _context.Performance
                .Include(p => p.Category)
                .Include(p => p.Purchases)
                .FirstOrDefaultAsync(m => m.PerformanceId == id);

            if (photo == null)
            {
                return NotFound();
            }

            return View(photo);
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/PerformancesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Eventix.Data;
using Eventix.Models;
using Microsoft.AspNetCore.Authorization;
using Azure.Storage.Blobs;
using Azure.Storage.Blobs.Models;


namespace Eventix.Controllers
{
    [Authorize]
    public class PerformancesController : Controller
    {
        private readonly EventixContext _context;
        private readonly BlobServiceClient _blobService;

        public PerformancesController(EventixContext context, BlobServiceClient blobService)
        {
            _context = context;
            _blobService = blobService;
        }

        // GET: Performances
        public async Task<IActionResult> Index()
        {
            return View(await _context.Performance.ToListAsync());
        }

        // GET: Performances/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var performance = await _context.Performance
                .Include(p => p.Purchases)
                .Include(p => p.Category)
                .FirstOrDefaultAsync(m => m.PerformanceId == id);

            if (performance == null)
            {
                return NotFound();
            }

            return View(performance);
        }

        // GET: Performances/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Performances/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PerformanceId,Name,Description,PerformanceDate,EndDate,ImagePath,FormFile,Host,Location,CategoryId")] Performance performance)
        {
            // Initialize values
            //performance.CreateDate = DateTime.Now;

            // Validate user input
            if (ModelState.IsValid)
            {
                //
                // Step 1: save the file (optionally)
                //
                if (performance.FormFile != null)
                {
                    // Create a unique filename using a Guid          
                    string filename = Guid.NewGuid().ToString() + Path.GetExtension(performance.FormFile.FileName); // f81d4fae-7dec-11d0-a765-00a0c91e6bf6.jpg

                    var container = _blobService.GetBlobContainerClient("performance-images");
                    await container.CreateIfNotExistsAsync();
                    await container.SetAccessPolicyAsync(PublicAccessType.Blob);

                    var blob = container.GetBlobClient(filename);
                    await blob.UploadAsync(performance.FormFile.OpenReadStream(), overwrite: true);

                    performance.ImagePath = blob.Uri.ToString();
                }

                else
                {
                    // Placeholder image if no image chosen
                    performance.ImagePath = "microphone.jpg";
                }

                //
                // Step 2: save record in database
                //

                _context.Add(performance);

                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index), "Home"); // Home index page
            }

            ViewData["CategoryId"] = new SelectList(_context.Set<Category>(), "CategoryId", "Title", performance.CategoryId);

            return View(performance);
        }


        // GET: Performances/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var performance = await _context.Performance.FindAsync(id);
            if (performance == null)
            {
                return NotFound();
            }
            return View(performance);
        }

        // POST: Performances/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PerformanceId,Name,Description,PerformanceDate,EndDate,ImagePath,FormFile,Host,Location,CategoryId")] Performance performance)
        {
            if (id != performance.PerformanceId)
                return NotFound();

            if (!ModelState.IsValid)
                return View(performance);

            try
            {
                //
                // Get the existing DB record
                //
                var existingPerformance = await _context.Performance
                    .AsNoTracking()
                    .FirstOrDefaultAsync(p => p.PerformanceId == id);

                if (existingPerformance == null)
                    return NotFound();

                //
                // Blob container reference
                //
                var container = _blobService.GetBlobContainerClient("performance-images");
                await container.CreateIfNotExistsAsync();
                await container.SetAccessPolicyAsync(PublicAccessType.Blob);

                //
                // If new file uploaded, upload new blob, delete old blob
                //
                if (performance.FormFile != null)
                {
                    string newFileName = Guid.NewGuid().ToString() + Path.GetExtension(performance.FormFile.FileName);

                    // Upload new blob
                    var newBlob = container.GetBlobClient(newFileName);
                    await newBlob.UploadAsync(performance.FormFile.OpenReadStream(), overwrite: true);

                    // Delete old blob
                    if (!string.IsNullOrEmpty(existingPerformance.ImagePath))
                    {
                        // Extract filename if ImagePath is URL
                        string oldFilename = existingPerformance.ImagePath.Split('/').Last();
                        var oldBlob = container.GetBlobClient(oldFilename);
                        await oldBlob.DeleteIfExistsAsync();
                    }

                    // Save new blob URL or filename
                    performance.ImagePath = newBlob.Uri.ToString();
                }
                else
                {
                    // KEEP the old filename / URL
                    performance.ImagePath = existingPerformance.ImagePath;
                }

                //
                // Update record in DB
                //
                _context.Update(performance);
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index), "Home");
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!_context.Performance.Any(e => e.PerformanceId == performance.PerformanceId))
                    return NotFound();
                else
                    throw;
            }
        }

        // GET: Performances/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var performance = await _context.Performance
                .FirstOrDefaultAsync(m => m.PerformanceId == id);
            if (performance == null)
            {
                return NotFound();
            }

            return View(performance);
        }

        // POST: Performances/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var performance = await _context.Performance.FindAsync(id);
            if (performance != null)
            {
                _context.Performance.Remove(performance);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index), "Home");
        }
    }
}

Views/Home/Details.cshtml
@model Eventix.Models.Performance

@{
    ViewData["Title"] = "Details";
}

<h1>Event Details</h1>

@if (!String.IsNullOrEmpty(Model.ImagePath))
{
    <div>
        <img src="@Model.ImagePath" alt="@Model.Name" class="w-25 l-25" />
    </div>
}

<div>
    <h4>Performance</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PerformanceDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PerformanceDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EndDate)
        </dd>
    </dl>
</div>
<div>
    <a asp-controller="Performances" asp-action="Edit" asp-route-id="@Model?.PerformanceId">Edit</a> |
    <a asp-controller="Home" asp-action="Index">Back to List</a>
</div>


<div class="col-12 mt-4">
    <h2>Tickets</h2>
    <hr />    
    @if (Model?.Purchases?.Any() == true)
    {
        <table class="table table-sm">
            <thead>
                <tr>
                    <th>Purchase ID</th>
                    <th>Performance ID</th>
                    <th>Number of Tickets</th>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Last 4 Card Digits</th>
                    <th>Purchase Date</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var purchase in Model.Purchases)
                {
                    <tr>
                        <td>@purchase.PurchaseId</td>
                        <td>@purchase.PerformanceId</td>
                        <td>@purchase.Tickets</td>
                        <td>@purchase.CustomerName</td>
                        <td>@purchase.Email</td>
                        <td>@purchase.CardLast4</td>
                        <td>@purchase.PurchaseDate.ToString("g")</td>
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <p class="text-muted">No Purchased Tickets</p>
    }
</div>

Views/Home/Index.cshtml
@model IEnumerable<Eventix.Models.Performance>

@{
    ViewData["Title"] = "Home Page";
}

<h1>Index</h1>

<p>
    <a asp-controller="Performances" asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FormFile)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PerformanceDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EndDate)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @if (!String.IsNullOrEmpty(item.ImagePath))
                    {
                        <img src="@item.ImagePath" alt="@item.Name" class="thumbnail" />
                    }
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PerformanceDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EndDate)
                </td>
                <td>
                    <a asp-controller="Performances" asp-action="Edit" asp-route-id="@item.PerformanceId">Edit</a> |
                    <a asp-controller="Home" asp-action="Details" asp-route-id="@item.PerformanceId">Details</a> |
                    <a asp-controller="Performances" asp-action="Delete" asp-route-id="@item.PerformanceId">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>